import type { IntelligenceEvent } from './types';

const now = new Date();
const minsAgo = (m: number) => new Date(now.getTime() - m * 60_000).toISOString();
const hoursAgo = (h: number) => minsAgo(h * 60);

export const MOCK_EVENTS: IntelligenceEvent[] = [
  {
    id: 'mock-agit-001',
    source_type: 'AGITATOR',
    source_name: 'mock_agitator',
    external_id: 'mock-agit-001',
    stable_id: 'mock-agit-001',
    title: 'Trump threatens 25% tariffs on all EU goods unless trade deal reached by June',
    body_preview:
      'President Trump posted on Truth Social threatening sweeping 25% tariffs on all European Union goods if a comprehensive trade agreement is not reached by June 1st. The statement sent US futures lower and strengthened the dollar.',
    url: null,
    published_at: minsAgo(20),
    spaces_key: '',
    event_type: 'POLITICAL',
    asset_type: 'FOREX',
    tickers: ['EUR', 'USD', 'SPY'],
    sectors: ['Trade', 'Macro'],
    entities: ['European Union', 'Donald Trump'],
    newsworthiness: 88,
    attention_score: 92,
    virality_score: 85,
    market_relevance: 90,
    impact_rating: 87,
    confidence: 72,
    status: 'CLASSIFIED',
    created_at: minsAgo(19),
    updated_at: minsAgo(19),
  },
  {
    id: 'mock-news-001',
    source_type: 'NEWS',
    source_name: 'mock_news',
    external_id: 'mock-news-001',
    stable_id: 'mock-news-001',
    title: 'Nvidia raises Q4 earnings guidance on surging AI chip demand',
    body_preview:
      'Nvidia has raised its Q4 earnings guidance, citing record demand for its H100 and upcoming H200 AI accelerators. CEO Jensen Huang attributed the surge to hyperscaler spending on AI infrastructure.',
    url: null,
    published_at: minsAgo(15),
    spaces_key: '',
    event_type: 'EARNINGS',
    asset_type: 'STOCK',
    tickers: ['NVDA', 'AMD', 'INTC'],
    sectors: ['Technology', 'Semiconductors'],
    entities: ['Nvidia', 'Jensen Huang'],
    newsworthiness: 82,
    attention_score: 78,
    virality_score: 70,
    market_relevance: 85,
    impact_rating: 80,
    confidence: 88,
    status: 'CLASSIFIED',
    created_at: minsAgo(14),
    updated_at: minsAgo(14),
  },
  {
    id: 'mock-agit-002',
    source_type: 'AGITATOR',
    source_name: 'mock_agitator',
    external_id: 'mock-agit-002',
    stable_id: 'mock-agit-002',
    title: 'Elon Musk: xAI\'s Grok 3 outperforms GPT-4o on all benchmarks — Tesla FSD next',
    body_preview:
      'Elon Musk posted on X that Grok 3 has surpassed GPT-4o across all major benchmarks and will be integrated into Tesla vehicles for Full Self-Driving within 6 months. TSLA jumped 5% in after-hours trading.',
    url: null,
    published_at: minsAgo(40),
    spaces_key: '',
    event_type: 'SOCIAL',
    asset_type: 'STOCK',
    tickers: ['TSLA', 'GOOG', 'MSFT'],
    sectors: ['Technology', 'AI', 'Automotive'],
    entities: ['Elon Musk', 'Tesla', 'xAI'],
    newsworthiness: 76,
    attention_score: 94,
    virality_score: 91,
    market_relevance: 78,
    impact_rating: 74,
    confidence: 65,
    status: 'CLASSIFIED',
    created_at: minsAgo(39),
    updated_at: minsAgo(39),
  },
  {
    id: 'mock-news-002',
    source_type: 'NEWS',
    source_name: 'mock_news',
    external_id: 'mock-news-002',
    stable_id: 'mock-news-002',
    title: 'OPEC+ announces surprise 1 million barrel per day oil output cut',
    body_preview:
      'OPEC+ has announced an unexpected reduction of 1 million barrels per day, citing concerns over global demand weakness and US inventory builds. Oil prices jumped 4% on the news.',
    url: null,
    published_at: minsAgo(45),
    spaces_key: '',
    event_type: 'MACRO',
    asset_type: 'COMMODITY',
    tickers: ['USO', 'XOM', 'CVX', 'CL'],
    sectors: ['Energy', 'Commodities'],
    entities: ['OPEC+'],
    newsworthiness: 84,
    attention_score: 80,
    virality_score: 68,
    market_relevance: 82,
    impact_rating: 83,
    confidence: 91,
    status: 'CLASSIFIED',
    created_at: minsAgo(44),
    updated_at: minsAgo(44),
  },
  {
    id: 'mock-agit-003',
    source_type: 'AGITATOR',
    source_name: 'mock_agitator',
    external_id: 'mock-agit-003',
    stable_id: 'mock-agit-003',
    title: 'Bank of England: rate cut path depends on services inflation trajectory',
    body_preview:
      'Bank of England Governor Andrew Bailey stated in a speech that the pace of future rate cuts will be determined by the trajectory of services inflation. Sterling fell 0.4% against the dollar on the cautious tone.',
    url: null,
    published_at: hoursAgo(1),
    spaces_key: '',
    event_type: 'CENTRAL_BANK',
    asset_type: 'FOREX',
    tickers: ['GBP', 'GBPUSD'],
    sectors: ['Macro', 'Monetary Policy'],
    entities: ['Bank of England', 'Andrew Bailey'],
    newsworthiness: 79,
    attention_score: 71,
    virality_score: 55,
    market_relevance: 81,
    impact_rating: 76,
    confidence: 85,
    status: 'CLASSIFIED',
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
  },
  {
    id: 'mock-news-003',
    source_type: 'NEWS',
    source_name: 'mock_news',
    external_id: 'mock-news-003',
    stable_id: 'mock-news-003',
    title: 'Federal Reserve holds rates steady, signals two cuts in 2025',
    body_preview:
      'The Federal Reserve kept its benchmark interest rate unchanged at 5.25%–5.50%, but the dot plot now indicates two 25 basis point cuts expected in 2025, sending bond yields lower and equities higher.',
    url: null,
    published_at: hoursAgo(2),
    spaces_key: '',
    event_type: 'MACRO',
    asset_type: 'INDEX',
    tickers: ['SPY', 'QQQ', 'TLT', 'DXY'],
    sectors: ['Macro', 'Monetary Policy'],
    entities: ['Federal Reserve'],
    newsworthiness: 91,
    attention_score: 88,
    virality_score: 74,
    market_relevance: 93,
    impact_rating: 89,
    confidence: 94,
    status: 'CLASSIFIED',
    created_at: hoursAgo(2),
    updated_at: hoursAgo(2),
  },
  {
    id: 'mock-agit-004',
    source_type: 'AGITATOR',
    source_name: 'mock_agitator',
    external_id: 'mock-agit-004',
    stable_id: 'mock-agit-004',
    title: 'Crypto influencer: BlackRock spot Ethereum ETF approval imminent, sources say',
    body_preview:
      'Prominent crypto influencer @WhalePump posted that multiple institutional sources indicate BlackRock\'s spot Ethereum ETF approval is imminent. ETH rallied 6% and COIN gained 4% on the rumour.',
    url: null,
    published_at: hoursAgo(2),
    spaces_key: '',
    event_type: 'CRYPTO',
    asset_type: 'CRYPTO',
    tickers: ['ETH', 'COIN', 'BTC'],
    sectors: ['Crypto', 'Regulation'],
    entities: ['BlackRock', 'SEC', 'WhalePump'],
    newsworthiness: 68,
    attention_score: 85,
    virality_score: 88,
    market_relevance: 72,
    impact_rating: 65,
    confidence: 48,
    status: 'CLASSIFIED',
    created_at: hoursAgo(2),
    updated_at: hoursAgo(2),
  },
  {
    id: 'mock-news-004',
    source_type: 'NEWS',
    source_name: 'mock_news',
    external_id: 'mock-news-004',
    stable_id: 'mock-news-004',
    title: 'Apple faces supply chain disruption as Taiwan supplier halts production',
    body_preview:
      'A key Apple supplier in Taiwan has halted production at two facilities due to equipment failures, raising concerns over iPhone 16 component availability ahead of the holiday season.',
    url: null,
    published_at: hoursAgo(3),
    spaces_key: '',
    event_type: 'SUPPLY_CHAIN',
    asset_type: 'STOCK',
    tickers: ['AAPL', 'FOXC', 'TSM'],
    sectors: ['Technology', 'Supply Chain'],
    entities: ['Apple', 'Taiwan'],
    newsworthiness: 77,
    attention_score: 73,
    virality_score: 61,
    market_relevance: 79,
    impact_rating: 71,
    confidence: 80,
    status: 'CLASSIFIED',
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
  },
  {
    id: 'mock-agit-005',
    source_type: 'AGITATOR',
    source_name: 'mock_agitator',
    external_id: 'mock-agit-005',
    stable_id: 'mock-agit-005',
    title: 'SEC Chair signals stricter oversight of AI-driven trading platforms',
    body_preview:
      'SEC Chair Gary Gensler warned in congressional testimony that AI-driven trading platforms could pose systemic risks and that the Commission is preparing new disclosure requirements for algorithmic trading systems.',
    url: null,
    published_at: hoursAgo(3),
    spaces_key: '',
    event_type: 'REGULATORY',
    asset_type: 'STOCK',
    tickers: ['HOOD', 'IBKR', 'SCHW'],
    sectors: ['Finance', 'Regulation', 'Technology'],
    entities: ['SEC', 'Gary Gensler'],
    newsworthiness: 74,
    attention_score: 69,
    virality_score: 58,
    market_relevance: 76,
    impact_rating: 70,
    confidence: 82,
    status: 'CLASSIFIED',
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
  },
  {
    id: 'mock-news-005',
    source_type: 'NEWS',
    source_name: 'mock_news',
    external_id: 'mock-news-005',
    stable_id: 'mock-news-005',
    title: 'SEC reportedly considering approval of spot Bitcoin ETF in Q1 2025',
    body_preview:
      'Sources familiar with SEC deliberations indicate the regulator is close to approving a spot Bitcoin ETF, with multiple asset managers submitting final amended filings. Bitcoin surged 8% on the report.',
    url: null,
    published_at: hoursAgo(4),
    spaces_key: '',
    event_type: 'REGULATORY',
    asset_type: 'CRYPTO',
    tickers: ['BTC', 'MSTR', 'COIN'],
    sectors: ['Crypto', 'Regulation'],
    entities: ['SEC', 'BlackRock', 'Fidelity'],
    newsworthiness: 86,
    attention_score: 89,
    virality_score: 83,
    market_relevance: 84,
    impact_rating: 82,
    confidence: 61,
    status: 'CLASSIFIED',
    created_at: hoursAgo(4),
    updated_at: hoursAgo(4),
  },
];

export const MOCK_HIGH_IMPACT = MOCK_EVENTS.filter(
  (e) => (e.impact_rating ?? 0) >= 60,
).slice(0, 5);
